/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

long*
factorial_1(char *host, int arg)
{
	CLIENT *clnt;
	long  *result_1;
	int  calc_fac_1_arg = arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACTORIAL, ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calc_fac_1(&calc_fac_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

    return result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

    printf("%d", *factorial_1 (host, 5));
exit (0);
}
