/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

long *
calc_fac_1_svc(int *argp, struct svc_req *rqstp)
{
	static long result;

	result = *argp + 10;

	return &result;
}
